export * from './About'
export * from './Background'
export * from './Contact'
export * from './Footer'
export * from './Hero'
export * from './Navbar'
export * from './Projects'
export * from './ScrollToTop'
export * from './Skills'

